part of bridge.view;

class TemplateProcessor {
  final Map<String, String> _scripts = {};

  Future include(String name,
                 String script,
                 {List<TemplatePreProcessor> preProcessors: const []}) async {
    script = (script == null) ? '' : script;
    for (var preProcessor in preProcessors)
      script = await preProcessor.process(script);
    _scripts[name] = script;
  }

  String get templateScript {
    var script = '''

@proxy
class Templates extends TemplateCollection {
  Map<String, TemplateGenerator> get templates => {
${_scripts.keys
    .map((name) => '    "$name": () async => new Template('
    'parsed: """${_scripts[name]}""", '
    'data: data),')
    .join('\n')}
  };
}''';
    var dateString = new DateTime.now()
    .toString().replaceAll(new RegExp('[^0-9]'), '_');
    if (script.contains('Future'))
      script = 'import "dart:async";\n$script';
    script = 'import "package:bridge/view.dart";\n$script';
    script = 'library templates_$dateString;\n\n$script';
    script = '// THIS FILE WAS GENERATED BY bridge.view AND SHOULD NOT BE MODIFIED\n\n$script';
    return script;
  }
}